load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "interfaces",
    srcs = ["store.go"],
    importpath = "github.com/mtr002/Job-Queue/internal/interfaces",
    visibility = ["//visibility:public"],
    deps = ["//internal/jobs"],
)


