load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "api",
    srcs = ["server.go"],
    importpath = "github.com/mtr002/Job-Queue/internal/api",
    visibility = ["//:__subpackages__"],
)
