// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/jobqueue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,3,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_jobqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobqueue_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitJobRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SubmitJobRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_jobqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobqueue_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitJobResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_jobqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobqueue_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_jobqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobqueue_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *JobStatusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *JobStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobStatusResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *JobStatusResponse) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *JobStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *JobStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ProcessJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessJobRequest) Reset() {
	*x = ProcessJobRequest{}
	mi := &file_proto_jobqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessJobRequest) ProtoMessage() {}

func (x *ProcessJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessJobRequest.ProtoReflect.Descriptor instead.
func (*ProcessJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobqueue_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ProcessJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessJobResponse) Reset() {
	*x = ProcessJobResponse{}
	mi := &file_proto_jobqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessJobResponse) ProtoMessage() {}

func (x *ProcessJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessJobResponse.ProtoReflect.Descriptor instead.
func (*ProcessJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobqueue_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_jobqueue_proto protoreflect.FileDescriptor

const file_proto_jobqueue_proto_rawDesc = "" +
	"\n" +
	"\x14proto/jobqueue.proto\x12\bjobqueue\"c\n" +
	"\x10SubmitJobRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12!\n" +
	"\fmax_attempts\x18\x03 \x01(\x05R\vmaxAttempts\"a\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9b\x02\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\b \x01(\x05R\vmaxAttempts\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"*\n" +
	"\x11ProcessJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"H\n" +
	"\x12ProcessJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xba\x02\n" +
	"\rWorkerService\x12D\n" +
	"\tSubmitJob\x12\x1a.jobqueue.SubmitJobRequest\x1a\x1b.jobqueue.SubmitJobResponse\x12D\n" +
	"\fGetJobStatus\x12\x17.jobqueue.GetJobRequest\x1a\x1b.jobqueue.JobStatusResponse\x12O\n" +
	"\x12NotifyJobCompleted\x12\x1b.jobqueue.ProcessJobRequest\x1a\x1c.jobqueue.ProcessJobResponse\x12L\n" +
	"\x0fNotifyJobFailed\x12\x1b.jobqueue.ProcessJobRequest\x1a\x1c.jobqueue.ProcessJobResponseB#Z!github.com/mtr002/Job-Queue/protob\x06proto3"

var (
	file_proto_jobqueue_proto_rawDescOnce sync.Once
	file_proto_jobqueue_proto_rawDescData []byte
)

func file_proto_jobqueue_proto_rawDescGZIP() []byte {
	file_proto_jobqueue_proto_rawDescOnce.Do(func() {
		file_proto_jobqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jobqueue_proto_rawDesc), len(file_proto_jobqueue_proto_rawDesc)))
	})
	return file_proto_jobqueue_proto_rawDescData
}

var file_proto_jobqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_jobqueue_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),   // 0: jobqueue.SubmitJobRequest
	(*SubmitJobResponse)(nil),  // 1: jobqueue.SubmitJobResponse
	(*GetJobRequest)(nil),      // 2: jobqueue.GetJobRequest
	(*JobStatusResponse)(nil),  // 3: jobqueue.JobStatusResponse
	(*ProcessJobRequest)(nil),  // 4: jobqueue.ProcessJobRequest
	(*ProcessJobResponse)(nil), // 5: jobqueue.ProcessJobResponse
}
var file_proto_jobqueue_proto_depIdxs = []int32{
	0, // 0: jobqueue.WorkerService.SubmitJob:input_type -> jobqueue.SubmitJobRequest
	2, // 1: jobqueue.WorkerService.GetJobStatus:input_type -> jobqueue.GetJobRequest
	4, // 2: jobqueue.WorkerService.NotifyJobCompleted:input_type -> jobqueue.ProcessJobRequest
	4, // 3: jobqueue.WorkerService.NotifyJobFailed:input_type -> jobqueue.ProcessJobRequest
	1, // 4: jobqueue.WorkerService.SubmitJob:output_type -> jobqueue.SubmitJobResponse
	3, // 5: jobqueue.WorkerService.GetJobStatus:output_type -> jobqueue.JobStatusResponse
	5, // 6: jobqueue.WorkerService.NotifyJobCompleted:output_type -> jobqueue.ProcessJobResponse
	5, // 7: jobqueue.WorkerService.NotifyJobFailed:output_type -> jobqueue.ProcessJobResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_jobqueue_proto_init() }
func file_proto_jobqueue_proto_init() {
	if File_proto_jobqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jobqueue_proto_rawDesc), len(file_proto_jobqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jobqueue_proto_goTypes,
		DependencyIndexes: file_proto_jobqueue_proto_depIdxs,
		MessageInfos:      file_proto_jobqueue_proto_msgTypes,
	}.Build()
	File_proto_jobqueue_proto = out.File
	file_proto_jobqueue_proto_goTypes = nil
	file_proto_jobqueue_proto_depIdxs = nil
}
